cp -rv ${HOME}/.zshrc ../
cp -rv ${HOME}/.vimrc ../
cp -rv ${HOME}/.config/gtk-2.0 ../
cp -rv ${HOME}/.config/gtk-3.0 ../
cp -rv ${HOME}/.config/zsh/functions ../zsh/
cp -rv ${HOME}/.config/zsh/settings.zsh ../zsh/
cp -rv ${HOME}/.config/micro/*.json ../micro/
cp -rv ${HOME}/.config/lsd ../
cp -rv ${HOME}/.config/mpv ../
cp -rv ${HOME}/.config/starship.toml ../
cp -rv ${HOME}/.config/spicetify/config-xpui.ini ../spicetify
