cp -rv ${HOME}/.zshrc ../
cp -rv ${HOME}/.vimrc ../
cp -rv ${HOME}/.config/zsh/functions ../zsh/
cp -rv ${HOME}/.config/zsh/settings.zsh ../zsh/
cp -rv ${HOME}/.config/micro ../
cp -rv ${HOME}/.config/lsd ../
cp -rv ${HOME}/.config/starship.toml ../
cp -rv ${HOME}/.config/spicetify/config-xpui.ini ../spicetify
cp -rv ${HOME}/.config/spicetify/Themes ../spicetify
cp -rv ${HOME}/.config/spicetify/Extensions ../spicetify
cp -rv ${HOME}/.config/spicetify/Backup ../spicetify
