cp -rv ${HOME}/.zshrc ../
cp -rv ${HOME}/.vimrc ../
cp -rv ${HOME}/.config/micro ../
cp -rv ${HOME}/.config/gtk-3.0 ../
cp -rv ${HOME}/.config/gtk-2.0 ../
cp -rv ${HOME}/.config/fontconfig ../
cp -rv ${HOME}/.config/lsd ../
cp -rv ${HOME}/.config/starship.toml ../
cp -rv ${HOME}/.config/spicetify/config-xpui.ini ../spicetify
cp -rv ${HOME}/.config/spicetify/Themes ../spicetify
cp -rv ${HOME}/.config/spicetify/Extensions ../spicetify
cp -rv ${HOME}/.config/spicetify/Backup ../spicetify
